replicaCount: 2

image:
  repository: ghcr.io/green-ecolution/project-website
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets:

serviceAccount:
  create: false
  name: ""

deployment:
  annotations: {}
  autoscaling:
    enabled: false
  replicaCount: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%

podLabels: {}
podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  annotations: {}

ingress:
  enabled: true
  className: "traefik"
  hosts: []
  addWww: false
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cert-manager
  tls:
    enabled: true
    secretName: landing-page-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  enabled: true
  config:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

livenessProbe:
  enabled: true
  config:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 20

startupProbe:
  enabled: false
  config: {}

volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
  - name: nginx-log
    emptyDir: {}
  - name: nginx-tmp
    emptyDir: {}

volumeMounts:
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: nginx-run
    mountPath: /var/run
  - name: nginx-log
    mountPath: /var/log/nginx
  - name: nginx-tmp
    mountPath: /tmp

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
