FROM node:25-alpine AS builder-web

WORKDIR /app/build
COPY ./package.json ./package.json
RUN yarn --frozen-lockfile

COPY . .
RUN yarn build:stage


FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/nginx.conf /etc/nginx/conf.d/
COPY --from=builder-web /app/build/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
