/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesSlugRouteImport } from './routes/releases_.$slug'

const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesSlugRoute = ReleasesSlugRouteImport.update({
  id: '/releases_/$slug',
  path: '/releases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/project': typeof ProjectRoute
  '/releases': typeof ReleasesRoute
  '/releases/$slug': typeof ReleasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/project': typeof ProjectRoute
  '/releases': typeof ReleasesRoute
  '/releases/$slug': typeof ReleasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/project': typeof ProjectRoute
  '/releases': typeof ReleasesRoute
  '/releases_/$slug': typeof ReleasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/project'
    | '/releases'
    | '/releases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/contact' | '/project' | '/releases' | '/releases/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/project'
    | '/releases'
    | '/releases_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  ProjectRoute: typeof ProjectRoute
  ReleasesRoute: typeof ReleasesRoute
  ReleasesSlugRoute: typeof ReleasesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases_/$slug': {
      id: '/releases_/$slug'
      path: '/releases/$slug'
      fullPath: '/releases/$slug'
      preLoaderRoute: typeof ReleasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  ProjectRoute: ProjectRoute,
  ReleasesRoute: ReleasesRoute,
  ReleasesSlugRoute: ReleasesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
