/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangDatenschutzRouteImport } from './routes/$lang/datenschutz'
import { Route as LangImpressumRouteImport } from './routes/$lang/impressum'
import { Route as LangProjectRouteImport } from './routes/$lang/project'
import { Route as LangReleasesRouteImport } from './routes/$lang/releases'
import { Route as LangReleasesSlugRouteImport } from './routes/$lang/releases_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDatenschutzRoute = LangDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangImpressumRoute = LangImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProjectRoute = LangProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReleasesRoute = LangReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReleasesSlugRoute = LangReleasesSlugRouteImport.update({
  id: '/releases_/$slug',
  path: '/releases/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/project': typeof LangProjectRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/releases/$slug': typeof LangReleasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/project': typeof LangProjectRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/releases/$slug': typeof LangReleasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/project': typeof LangProjectRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/releases_/$slug': typeof LangReleasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/impressum'
    | '/$lang/project'
    | '/$lang/releases'
    | '/$lang/'
    | '/$lang/releases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/impressum'
    | '/$lang/project'
    | '/$lang/releases'
    | '/$lang'
    | '/$lang/releases/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/impressum'
    | '/$lang/project'
    | '/$lang/releases'
    | '/$lang/'
    | '/$lang/releases_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/datenschutz': {
      id: '/$lang/datenschutz'
      path: '/datenschutz'
      fullPath: '/$lang/datenschutz'
      preLoaderRoute: typeof LangDatenschutzRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/impressum': {
      id: '/$lang/impressum'
      path: '/impressum'
      fullPath: '/$lang/impressum'
      preLoaderRoute: typeof LangImpressumRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/project': {
      id: '/$lang/project'
      path: '/project'
      fullPath: '/$lang/project'
      preLoaderRoute: typeof LangProjectRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/releases': {
      id: '/$lang/releases'
      path: '/releases'
      fullPath: '/$lang/releases'
      preLoaderRoute: typeof LangReleasesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/releases_/$slug': {
      id: '/$lang/releases_/$slug'
      path: '/releases/$slug'
      fullPath: '/$lang/releases/$slug'
      preLoaderRoute: typeof LangReleasesSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangContactRoute: typeof LangContactRoute
  LangDatenschutzRoute: typeof LangDatenschutzRoute
  LangImpressumRoute: typeof LangImpressumRoute
  LangProjectRoute: typeof LangProjectRoute
  LangReleasesRoute: typeof LangReleasesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangReleasesSlugRoute: typeof LangReleasesSlugRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangContactRoute: LangContactRoute,
  LangDatenschutzRoute: LangDatenschutzRoute,
  LangImpressumRoute: LangImpressumRoute,
  LangProjectRoute: LangProjectRoute,
  LangReleasesRoute: LangReleasesRoute,
  LangIndexRoute: LangIndexRoute,
  LangReleasesSlugRoute: LangReleasesSlugRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
