name: "Build project on PR"

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            actions: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Build project
              run: yarn build
