name: "Notify on new issue"
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_ISSUE_WEBHOOK }}
          content: |
            Es wurde ein neues Issue #${{ github.event.issue.number }} erstellt.
            **${{ github.event.issue.title }}** 

            ${{ github.event.issue.html_url }}
          username: "GitHub Actions"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
